apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: h5
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YmFzZV9yb290X3Bhc3M=
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: bXlwYXNz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: h5
data:
  MYSQL_DATABASE: appdb
